---
  - hosts: 34.221.25.127
    become: true
    tasks:
      - name: Make sure pymysql is present
        become: true # needed if the other tasks are not played as root
        pip:
          name: pymysql
          state: present
        
      - name: create a backup
        mysql_db:
          name: PROD
          state: dump
          target: /home/cloud_user/PROD.sql
          login_host: 172.31.99.81
          login_user: saxenan
          login_password: Exadata2017


    
      - name: check permission
        ansible.builtin.file:
          path: "/home/cloud_user/PROD.sql"
          owner: "cloud_user"
          group: "cloud_user"
          mode: '0777'
      
      - name: copy the database to the development server
        raw: rsync /home/cloud_user/PROD.sql cloud_user@54.188.168.151:/home/cloud_user/PROD.sql

 
      - name: import the database
        mysql_db:
          name: DEV
          state: import
          target: /home/cloud_user/PROD.sql
          login_host: 172.31.108.133
          login_user: saxenan
          login_password: 'Exadata2017'
        delegate_to: 54.188.168.151