---
  - hosts: 54.191.15.52
    become: true
    tasks:
      - name: Make sure pymysql is present
        become: true # needed if the other tasks are not played as root
        pip:
          name: pymysql
          state: present
        
      - name: create a backup
        mysql_db:
          name: EMPLOYEESDB
          state: dump
          target: /home/cloud_user/PROD.sql
          login_host: 172.31.110.40
          login_user: saxenan
          login_password: Exadata2017


    
      - name: check permission
        ansible.builtin.file:
          path: "/home/cloud_user/PROD.sql"
          owner: "cloud_user"
          group: "cloud_user"
          mode: '0777'

      # - name: Transfer file from ServerA to ServerB
      #   synchronize:
      #     src: "/home/cloud_user/PROD.sql"
      #     dest: "/home/cloud_user/PROD.sql"
      #     mode: pull
      #   delegate_to: 34.212.120.255
      #   become: false

 
      - name: import the database
        mysql_db:
          name: DEV
          state: import
          target: /home/cloud_user/PROD.sql
          login_host: 172.31.110.40
          login_user: saxenan
          login_password: 'Exadata2017'