---
  - hosts: 52.12.1.52,35.87.112.86
    become: true
    tasks:
      - name: Make sure pymysql is present
        become: true # needed if the other tasks are not played as root
        pip:
          name: pymysql
          state: present
        
      - name: create a backup
        mysql_db:
          name: PROD
          state: dump
          target: /home/cloud_user/PROD.sql
          login_host: 172.31.99.81
          login_user: saxenan
          login_password: Exadata2017
        delegate_to: 52.12.1.52


    
      - name: check permission
        ansible.builtin.file:
          path: "/home/cloud_user/PROD.sql"
          owner: "cloud_user"
          group: "cloud_user"
          mode: '0777'
        delegate_to: 52.12.1.52
      

      - name: Copy the file from mwiapp01 to mwiapp02 using Method Push
        tags: sync-push
        synchronize:
          src: "{{ item }}"
          dest: "{{ item }}"
          mode: push
        delegate_to: 52.12.1.52
        register: syncfile
        with_items:
         - "/home/cloud_user/PROD.sql"

 
      - name: import the database
        mysql_db:
          name: DEV
          state: import
          target: /home/cloud_user/PROD.sql
          login_host: 172.31.108.133
          login_user: saxenan
          login_password: 'Exadata2017'
        delegate_to: 35.87.112.86